### PR TITLE
[Elao - App - Docker] Remove legacy deliveries actions & docs + add env vars docs

### PR DESCRIPTION
**Pull request by ogizanagi**
> **Warning**
> This PR drop the previous deliveries system & GitHub actions
> Consult the new docs to migrate your projects GitHub workflows

### CODE REVIEW

**Comment by ogizanagi** [comment]
Rendered doc example : 

# Deliveries

## Prerequisites

In order for `on.inputs.tier.type = 'environment'` to work, you need to have your environments configured in your
repository (https://github.com/<org>/<repo>/settings/environments).
Most common environments are `production` and `staging`, but you might have multiple stages as well (`staging-1`, `staging-2`, …)

## Usage

> Please now consult:
> - [./release/README.md](./release/README.md) for release workflow
> - [./deploy/README.md](./deploy/README.md) for deploy workflow

## Exposing secrets

In case you need to expose secrets as env vars, for instance to provide an auth token during the release process,
you can use the `with.env` key during setup to provide a string of env vars to be forwarded, as shown below.

```yaml
jobs:
  test:
    # […]
    steps:
      # […]
      - name: 'Setup container with Manala'
        uses: ./.manala/github/deliveries/setup
        with:
          env: |
            COMPOSER_AUTH='{ "github-oauth": { "github.com": "${{ secrets.COMPOSER_AUTH_TOKEN }}" } }'
```

```yaml
jobs:
  release:
    # […]
    steps:
      # […]
      - name: 'Setup container with Manala'
        uses: ./.manala/github/deliveries/setup
        with:
          # […]
          env: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            COMPOSER_AUTH='{ "github-oauth": { "github.com": "${{ secrets.COMPOSER_AUTH_TOKEN }}" } }'
```

Use Github [steps conditions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif)
and the `./.manala/github/deliveries` action in order to expose different secrets depending on the app / tier:

```yaml
jobs:
  release:
    # […]
    steps:
      # […]
      - name: Setup with staging secrets
        uses: ./.manala/github/deliveries
        if: ${{ github.event.inputs.tier == 'staging' }}
        with:
          # […]
          env: SENTRY_AUTH_TOKEN=${{ secrets.STAGING_SENTRY_AUTH_TOKEN }}

      - name: Setup with production secrets
        uses: ./.manala/github/deliveries/setup
        if: ${{ github.event.inputs.tier == 'production' }}
        with:
          # […]
          env: SENTRY_AUTH_TOKEN=${{ secrets.production_SENTRY_AUTH_TOKEN }}

      - name: 'Release'
        uses: ./.manala/github/deliveries/release
        with:
          app: ${{ github.event.inputs.app }}
          tier: ${{ github.event.inputs.tier }}
```

## Getting an OAuth token

Sometimes, the `secrets.GITHUB_TOKEN` might not be enough to perform some actions,
such as reading another private repository, since it only has permissions on the current repository.

In this regard, we use the GitHub OAuth [Workflow Knight](https://github.com/apps/workflows-knight) app registered
on the organization level, to generate a token with the required permissions, with an extra step:

```yaml
jobs:
  test:
    # […]
    steps:
      # […]
      - name: 'Get Workflows Knight app token'
        id: get_app_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.WORKFLOWS_KNIGHT_APP_PEM_BASE_64 }}
          APP_ID: ${{ secrets.WORKFLOWS_KNIGHT_APP_ID }}

      - name: 'Setup container with Manala'
        uses: ./.manala/github/deliveries/setup
        with:
          # […]
          env: |
            COMPOSER_AUTH='{ "github-oauth": { "github.com": "${{ steps.get_app_token.outputs.app_token }}" } }'
      # […]
```

**Review by benji07 — APPROVED** [review]

**Comment by ogizanagi** [comment]
# Integration

## Advices

Please consult [advices.md](./advices.md) for some advices & tips beforehand.

## Usage

### Setup the container

In order to execute commands in the CI in a similar environment as your local one,
you need to setup a container in your workflows, using the `./.manala/github/integration/setup` action:

```yaml
# […]

jobs:

  my-job:
    # […]

    steps:

      # […]

      - name: 'Setup container with Manala'
        uses: ./.manala/github/integration/setup
        timeout-minutes: 8
        with:
          services: mariadb
```

> **Note**
> By default, no service is started in the integration container.
> Specify explicitly the `services` option to start required ones.
> For instance, if you need to use a database for functional testing, you can start a `mariadb` service.

### Execute commands

Once your container is setup, you can execute commands in it using the `./.manala/github/integration/run` action:

```yaml
# […]

jobs:

  my-job:
    # […]

    steps:

      # […]

      - name: 'Install dependencies & setup project'
        uses: ./.manala/github/integration/run
        timeout-minutes: 3
        with:
          app: back
          run: make install@integration
```

## Exposing secrets

Consult [env.md](./env.md) for exposing secrets through env vars

#### Examples

### Test workflow

`.github/workflows/test.yaml`:

```yaml
on:
  push:
    branches: [master]
    #branches: [master, staging]
    # On specific apps changes in a monorepo:
    #paths: [.github/**, .manala/**, back/**, front/**]
    # Only on dependencies changes:
    #paths: ['**/composer.lock', '**/package-lock.json', '**/yarn.lock', '.github/**', '.manala/**']
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  #schedule:
  #  - cron: 0 0 * * 1 # Every Monday 00:00
  #workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test-back:
    name: 'Test'
    runs-on: ubuntu-latest
    timeout-minutes: 25
    # Do not run on WIP or Draft PRs
    if: "!github.event.pull_request || (!contains(github.event.pull_request.labels.*.name, 'WIP') && github.event.pull_request.draft == false)"

    steps:

      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup container with Manala'
        uses: ./.manala/github/integration/setup
        timeout-minutes: 8
        with:
          services: mariadb

      - name: 'Install dependencies & setup project'
        uses: ./.manala/github/integration/run
        timeout-minutes: 3
        with:
          app: back
          run: make install@integration

      - name: 'Run tests'
        uses: ./.manala/github/integration/run
        timeout-minutes: 12
        with:
          app: back
          run: make test.phpunit@integration
```

**Comment by ogizanagi** [comment]
# Advices & tips

The samples exposed are generic and must not be blindly copy/pasted to your project.
Please consider the following advices and example to adapt to your project needs.

## Draft and WIP PRs

Save your GitHub Actions quota and runners by avoiding running your workflow on draft PRs:

```yaml
# […]

jobs:
  my-job:
    runs-on: ubuntu-latest

    # Do not run Draft PRs:
    if: "!github.event.pull_request || github.event.pull_request.draft == false"
    # or per label:
    if: "!github.event.pull_request || !contains(github.event.pull_request.labels.*.name, 'WIP'"
    # or both:
    if: "!github.event.pull_request || !contains(github.event.pull_request.labels.*.name, 'WIP') && github.event.pull_request.draft == false)"
```

## Timeout

Avoid running your workflow indefinitely (might be a setup/runner issue) or detect abnormally long executions
by setting timeouts on your jobs and steps:

```yaml
# […]

jobs:
  my-job:
    runs-on: ubuntu-latest
    # Adapt the job timeout to your workflow
    timeout-minutes: 10

    steps:
      - name: Some heavy step
        timeout-minutes: 8
```

## Schedule

Properly identify when your workflow should be executed and schedule those than should only run periodically / on some file changes.
Typically, for dependencies checks (security/audit), limit your workflow to lock files changes and schedule a security check each week:

```yaml
on:
  # […]

  schedule:
    - cron: '0 0 * * 1' # At 00:00 on each Monday.

  # You can also allow to run this workflow manually using:
  workflow_dispatch: ~

# […]
```

**Comment by ogizanagi** [comment]
# Exposing secrets

In case you need to expose secrets as env vars, for instance to provide an auth token during the release process,
or a Composer authentication token for installing private dependencies,
you can use the `with.env` key during setup to provide a string of env vars to be forwarded, as shown below.

> **Note**
> You can use the `with.env` key on both `./.manala/github/integration/setup` (integration)
> and `./.manala/github/deliveries/setup` (delivery) actions.

**In a test workflow** to expose a Composer authentication token:

```yaml
jobs:
  your-job:
    # […]
    steps:
      # […]
      - name: 'Setup container with Manala'
        uses: ./.manala/github/integration/setup
        with:
          # […]
          env: |
            COMPOSER_AUTH='{ "github-oauth": { "github.com": "${{ secrets.COMPOSER_AUTH_TOKEN }}" } }'
```

**In a release workflow** to expose Sentry and Composer authentication tokens:

```yaml
jobs:
  release:
    # […]
    steps:
      # […]
      - name: 'Setup container with Manala'
        uses: ./.manala/github/deliveries/setup
        with:
          # […]
          env: |
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            COMPOSER_AUTH='{ "github-oauth": { "github.com": "${{ secrets.COMPOSER_AUTH_TOKEN }}" } }'
```

Use GitHub [steps conditions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif)
and the `./.manala/github/deliveries` action in order to expose different secrets depending on the app / tier:

```yaml
jobs:
  release:
    # […]
    steps:
      # […]
      - name: Setup with staging secrets
        uses: ./.manala/github/deliveries/setup
        if: ${{ github.event.inputs.tier == 'staging' }}
        with:
          # […]
          env: SENTRY_AUTH_TOKEN=${{ secrets.STAGING_SENTRY_AUTH_TOKEN }}

      - name: Setup with production secrets
        uses: ./.manala/github/deliveries/setup
        if: ${{ github.event.inputs.tier == 'production' }}
        with:
          # […]
          env: SENTRY_AUTH_TOKEN=${{ secrets.production_SENTRY_AUTH_TOKEN }}

      - name: 'Release'
        uses: ./.manala/github/deliveries/release
        with:
          app: ${{ github.event.inputs.app }}
          tier: ${{ github.event.inputs.tier }}
```

## Getting an OAuth token

Sometimes, the `secrets.GITHUB_TOKEN` might not be enough to perform some actions,
such as reading another private repository, since it only has permissions on the current repository.

In this regard, we use the GitHub OAuth [Workflow Knight](https://github.com/apps/workflows-knight) app registered
on the organization level, to generate a token with the required permissions, with an extra step:

```yaml
jobs:
  test:
    # […]
    steps:
      # […]
      - name: 'Get Workflows Knight app token'
        id: get_app_token
        uses: machine-learning-apps/actions-app-token@master
        with:
          APP_PEM: ${{ secrets.WORKFLOWS_KNIGHT_APP_PEM_BASE_64 }}
          APP_ID: ${{ secrets.WORKFLOWS_KNIGHT_APP_ID }}

      - name: 'Setup container with Manala'
        uses: ./.manala/github/deliveries/setup
        with:
          # […]
          env: |
            COMPOSER_AUTH='{ "github-oauth": { "github.com": "${{ steps.get_app_token.outputs.app_token }}" } }'
      # […]
```

**Comment by ogizanagi** [comment]
# Deliveries

## Prerequisites

In order for `on.inputs.tier.type = 'environment'` to work, you need to have your environments configured in your
repository (https://github.com/<org>/<repo>/settings/environments).
Most common environments are `production` and `staging`, but you might have multiple stages as well (`staging-1`, `staging-2`, …)

## Usage

 Please now consult:
 - [./release/README.md](./release/README.md) for release workflow
 - [./deploy/README.md](./deploy/README.md) for deploy workflow
 - [env.md](./../integration/env.md) for exposing secrets through env vars

**Pull request merged**
